fix: upload to google sheets
The Google Cloud has a payload upload limit. We need to upload the data in batches instead of uploading each sheet at once.
By default it uploads 5000 lines/rows on each iteration.

This commit fixes the error:

gspread.exceptions.APIError: {'code': 500, 'message': 'Internal error encountered.', 'status': 'INTERNAL'}

fccn/nau-technical#854